version: '3.4'

services:
  reactapp:
    image: reactapp
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debugger
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
    environment:
      - NODE_ENV=development
    env_file: .env

  test-runner:
    image: test-runner
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    volumes:
      - .:/app:cached
    env_file: .env
